apiVersion: v1 
kind: Service 
metadata: 
  name: selenium-hub 
  labels: 
    app: selenium-hub 
spec: 
  selector: 
    app: selenium-hub 
  ports: 
  - port: 4444 
    protocol: TCP 
    targetPort: 4444 
    name: port0 
  type: LoadBalancer 
  loadBalancerIP: "104.197.182.185" 
  sessionAffinity: None
